id: 49425
name: RemoteU System
description: RemoteU System Workspace
revision: 4
lastModifiedDate: '2020-01-15T14:12:18Z'
lastModifiedUser: alex.netrebskiy@aurea.com
lastModifiedAgent: structurizr-web/1736
model:
    people:
        - 
            id: '108'
            tags: 'Element,Person'
            name: RemoteU IC
            description: Remotecamp student
            location: Unspecified
        - 
            id: '110'
            tags: 'Element,Person'
            name: RemoteU QE
            description: QE team member
            location: Unspecified
        - 
            id: '109'
            tags: 'Element,Person'
            name: RemoteU SEM
            location: Unspecified
    softwareSystems:
        - 
            id: '111'
            tags: 'Element,Software System'
            name: AWS
            location: External
            containers:
                - 
                    id: '112'
                    tags: 'Element,Container'
                    name: Secrets Managers
                    description: Here should be description
                    technology: AWS Secrets Managers
        - 
            id: '139'
            tags: 'Element,Software System,Internal'
            name: RemoteU System
            relationships:
                - 
                    id: '157'
                    tags: Relationship
                    sourceId: '139'
                    destinationId: '115'
                    description: Updates RC Task / RC Review tickets
                    technology: JIRA API
                    interactionStyle: Synchronous
            location: Internal
            containers:
                - 
                    id: '140'
                    tags: 'Element,Container,Internal'
                    name: rc-jira-rc-review-webhook
                    relationships:
                        - 
                            id: '156'
                            tags: Relationship
                            sourceId: '140'
                            destinationId: '115'
                            description: Updates RC Task / RC Review tickets
                            technology: JIRA API
                            interactionStyle: Synchronous
                    technology: AWS Lambda
                    components:
                        - 
                            id: '141'
                            tags: 'Element,Component,Internal'
                            name: ProcessRcReview
                            relationships:
                                - 
                                    id: '155'
                                    tags: Relationship
                                    sourceId: '141'
                                    destinationId: '115'
                                    description: Updates RC Task / RC Review tickets
                                    technology: JIRA API
                                    interactionStyle: Synchronous
                                - 
                                    id: '150'
                                    tags: Relationship
                                    sourceId: '141'
                                    destinationId: '143'
                                    description: Pop message
                                    interactionStyle: Synchronous
                            technology: 'Lambda, Python'
                            size: 0
                        - 
                            id: '142'
                            tags: 'Element,Component,Internal'
                            name: RcReviewIssue
                            relationships:
                                - 
                                    id: '151'
                                    tags: Relationship
                                    sourceId: '142'
                                    destinationId: '143'
                                    description: Push message
                                    interactionStyle: Synchronous
                            technology: 'Lambda, Python'
                            size: 0
                        - 
                            id: '143'
                            tags: 'Element,Component,Internal'
                            name: RcReviewSqsQueue
                            technology: SQS
                            size: 0
                - 
                    id: '158'
                    tags: 'Element,Container,Internal'
                    name: remoteu-py-lambda-common
                    technology: 'Python, Package'
                    components:
                        - 
                            id: '159'
                            tags: 'Element,Component,SHARED_LIBRARY,Internal'
                            name: lambda-common
                            technology: Python
                            size: 0
        - 
            id: '114'
            tags: 'Element,Software System'
            name: XO Chat
            url: 'https://xo.chat.crossover.com/core'
            location: External
        - 
            id: '115'
            tags: 'Element,Software System'
            name: XO Jira
            url: 'https://crossover.atlassian.net/'
            relationships:
                - 
                    id: '152'
                    tags: Relationship
                    sourceId: '115'
                    destinationId: '142'
                    description: Notify about RC Task / RC Review transitions
                    interactionStyle: Synchronous
                - 
                    id: '154'
                    tags: Relationship
                    sourceId: '115'
                    destinationId: '139'
                    description: Notify about RC Task / RC Review transitions
                    interactionStyle: Synchronous
                - 
                    id: '153'
                    tags: Relationship
                    sourceId: '115'
                    destinationId: '140'
                    description: Notify about RC Task / RC Review transitions
                    interactionStyle: Synchronous
            location: External
    deploymentNodes:
        - 
            id: '136'
            tags: 'Element,Deployment Node'
            name: US-EAST-1
            environment: AWS
            instances: 1
            containerInstances:
                - 
                    id: '144'
                    tags: Container Instance
                    environment: AWS
                    containerId: '140'
                    instanceId: 1
                    properties: {}
            children: []
documentation:
    sections: []
    decisions: []
    images: []
views:
    componentViews:
        - 
            key: RcReviewWebhook
            paperSize: A5_Landscape
            animations:
                - 
                    order: 1
                    elements:
                        - '143'
                        - '141'
                        - '142'
                    relationships:
                        - '150'
                        - '151'
                - 
                    order: 2
                    elements:
                        - '115'
                    relationships:
                        - '155'
                        - '152'
            containerId: '140'
            elements:
                - 
                    id: '143'
                    x: 90
                    'y': 710
                - 
                    id: '115'
                    x: 1735
                    'y': 660
                - 
                    id: '141'
                    x: 770
                    'y': 935
                - 
                    id: '142'
                    x: 770
                    'y': 375
            relationships:
                - 
                    id: '152'
                - 
                    id: '151'
                - 
                    id: '150'
                - 
                    id: '155'
    configuration:
        branding: {}
        styles:
            elements:
                - 
                    tag: Person
                    background: '#08427b'
                    color: '#ffffff'
                    shape: Person
                - 
                    tag: Software System
                    background: '#999999'
                    color: '#ffffff'
                - 
                    tag: DB
                    shape: Cylinder
                - 
                    tag: Internal
                    background: '#438dd5'
                    color: '#ffffff'
                - 
                    tag: SHARED_LIBRARY
                    shape: Folder
            relationships:
                - 
                    tag: Relationship
                    dashed: true
        terminology: {}
        lastSavedView: RcReviewWebhook
    systemLandscapeViews: []
    systemContextViews: []
    containerViews: []
    dynamicViews: []
    deploymentViews: []
    filteredViews: []
