id: 48681
name: RemoteU System
description: RemoteU System Workspace
revision: 20
lastModifiedDate: '2019-11-07T08:39:28Z'
lastModifiedUser: alex.netrebskiy@aurea.com
lastModifiedAgent: structurizr-web/1666
model:
    people:
        - 
            id: '108'
            tags: 'Element,Person'
            name: RemoteU IC
            description: Remotecamp student
            location: Unspecified
        - 
            id: '110'
            tags: 'Element,Person'
            name: RemoteU QE
            description: QE team member
            location: Unspecified
        - 
            id: '109'
            tags: 'Element,Person'
            name: RemoteU SEM
            location: Unspecified
    softwareSystems:
        - 
            id: '111'
            tags: 'Element,Software System'
            name: AWS
            location: External
            containers:
                - 
                    id: '112'
                    tags: 'Element,Container'
                    name: Secrets Managers
                    description: Here should be description
                    technology: AWS Secrets Managers
        - 
            id: '113'
            tags: 'Element,Software System,Internal'
            name: rc-jira-rc-review-webhook
            relationships:
                - 
                    id: '123'
                    tags: Relationship
                    sourceId: '113'
                    destinationId: '108'
                    description: Enqueue
                    interactionStyle: Synchronous
            location: External
            containers:
                - 
                    id: '117'
                    tags: 'Element,Container,Internal,Lambda'
                    name: ProcessRcReview
                    description: Here should be description
                    relationships:
                        - 
                            id: '125'
                            tags: Relationship
                            sourceId: '117'
                            destinationId: '112'
                            description: Get credentials
                            interactionStyle: Synchronous
                        - 
                            id: '120'
                            tags: Relationship
                            sourceId: '117'
                            destinationId: '114'
                            description: Notifies about errors
                            interactionStyle: Synchronous
                        - 
                            id: '119'
                            tags: Relationship
                            sourceId: '117'
                            destinationId: '118'
                            description: Dequeue
                            interactionStyle: Synchronous
                    technology: AWS Lambda
                - 
                    id: '116'
                    tags: 'Element,Container,Internal,Lambda'
                    name: RcReviewIssue
                    description: Here should be description
                    relationships:
                        - 
                            id: '124'
                            tags: Relationship
                            sourceId: '116'
                            destinationId: '118'
                            description: Enqueue
                            interactionStyle: Synchronous
                    technology: AWS Lambda
                - 
                    id: '118'
                    tags: 'Element,Container,Internal,SQS'
                    name: RcReviewSqsQueue
                    description: Here should be description
                    technology: AWS SQS
        - 
            id: '114'
            tags: 'Element,Software System'
            name: XO Chat
            url: 'https://xo.chat.crossover.com/core'
            location: External
        - 
            id: '115'
            tags: 'Element,Software System'
            name: XO Jira
            url: 'https://crossover.atlassian.net/'
            relationships:
                - 
                    id: '121'
                    tags: Relationship
                    sourceId: '115'
                    destinationId: '116'
                    description: Notifies about changes
                    technology: Webhook
                    interactionStyle: Synchronous
            location: External
    deploymentNodes: []
documentation:
    sections: []
    decisions: []
    images: []
views:
    containerViews:
        - 
            softwareSystemId: '113'
            key: RcReview
            paperSize: A4_Portrait
            animations:
                - 
                    order: 1
                    elements:
                        - '114'
                        - '115'
                        - '116'
                        - '117'
                        - '118'
                    relationships:
                        - '121'
                        - '124'
                        - '119'
                        - '120'
                - 
                    order: 2
                    elements:
                        - '112'
                    relationships:
                        - '125'
            elements:
                - 
                    id: '112'
                    x: 310
                    'y': 950
                - 
                    id: '114'
                    x: 1340
                    'y': 2916
                - 
                    id: '115'
                    x: 1130
                    'y': 675
                - 
                    id: '116'
                    x: 1085
                    'y': 1700
                - 
                    id: '117'
                    x: 425
                    'y': 2155
                - 
                    id: '118'
                    x: 1230
                    'y': 2160
            relationships:
                - 
                    id: '119'
                    vertices:
                        - 
                            x: 975
                            'y': 2305
                - 
                    id: '120'
                - 
                    id: '121'
                - 
                    id: '124'
                - 
                    id: '125'
    configuration:
        branding: {}
        styles:
            elements:
                - 
                    tag: Person
                    background: '#08427b'
                    color: '#ffffff'
                    shape: Person
                - 
                    tag: Software System
                    background: '#999999'
                    color: '#ffffff'
                - 
                    tag: DB
                    shape: Cylinder
                - 
                    tag: Internal
                    background: '#438dd5'
                    color: '#ffffff'
            relationships:
                - 
                    tag: Relationship
                    dashed: true
        terminology: {}
        lastSavedView: RcReview
    systemLandscapeViews: []
    systemContextViews: []
    componentViews: []
    dynamicViews: []
    deploymentViews: []
    filteredViews: []
